import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("koncesii", "routes/concessions.tsx"),
  route("koncesii.csv", "routes/concessions-csv.ts"),
  route("koncesii/vid/:kind", "routes/concessions-kind.tsx"),
  route("koncesii/:slug", "routes/concession-detail.tsx"),
  route("koncesii/:slug/json", "routes/concession-json.ts"),
  route("koncesii/:slug/dokumenti/:key", "routes/document-text.tsx"),
  route("koncedenti", "routes/grantors.tsx"),
  route("koncedenti.csv", "routes/grantors-csv.ts"),
  route("koncedenti/:slug", "routes/grantor-detail.tsx"),
  route("kompanii", "routes/companies.tsx"),
  route("kompanii.csv", "routes/companies-csv.ts"),
  route("kompanii/:slug", "routes/company-detail.tsx"),
  route("analizi", "routes/blog.tsx"),
  route("analizi/:slug", "routes/blog-post.tsx"),
  route("promeni", "routes/changes.tsx"),
  route("karta", "routes/map.tsx"),
  route("karta.geojson", "routes/map-geojson.ts"),
  route("karta-tochki.json", "routes/map-points.ts"),
  route("indikatori", "routes/flags.tsx"),
  route("indikatori.csv", "routes/flags-csv.ts"),
  route("tarsene", "routes/search.tsx"),
  route("metodologiya", "routes/methodology.tsx"),
  route("obshtini", "routes/municipalities.tsx"),
  route("obshtini/:slug", "routes/municipality-detail.tsx"),
  // Английските адреси до 25.09.2026 (и по-старите slug-ове на партидите):
  // едно 301 директно към новия адрес, без вериги (routes/legacy-redirect.ts).
  ...[
    "concessions",
    "concessions.csv",
    "concessions/*",
    "grantors",
    "grantors.csv",
    "grantors/*",
    "companies",
    "companies.csv",
    "companies/*",
    "blog",
    "blog/*",
    "changes",
    "map",
    "map.geojson",
    "map-points.json",
    "flags",
    "flags.csv",
    "search",
    "methodology",
  ].map((path) =>
    route(path, "routes/legacy-redirect.ts", { id: `legacy:${path}` }),
  ),
  route("robots.txt", "routes/robots.ts"),
  route("sitemap.xml", "routes/sitemap.ts"),
  route("sitemap-pages.xml", "routes/sitemap-section.ts", {
    id: "sitemap-pages",
  }),
  route("sitemap-concessions.xml", "routes/sitemap-section.ts", {
    id: "sitemap-concessions",
  }),
  route("sitemap-grantors.xml", "routes/sitemap-section.ts", {
    id: "sitemap-grantors",
  }),
  route("sitemap-companies.xml", "routes/sitemap-section.ts", {
    id: "sitemap-companies",
  }),
  route("sitemap-municipalities.xml", "routes/sitemap-section.ts", {
    id: "sitemap-municipalities",
  }),
  route("sitemap-documents.xml", "routes/sitemap-section.ts", {
    id: "sitemap-documents",
  }),
  route("healthz", "routes/healthz.ts"),
  route("openapi.json", "routes/openapi.ts"),
  route(".well-known/api-catalog", "routes/api-catalog.ts"),
  route(".well-known/agent-skills/index.json", "routes/agent-skills-index.ts"),
  route(
    ".well-known/agent-skills/koncesii-data/SKILL.md",
    "routes/agent-skill-data.ts",
  ),
] satisfies RouteConfig;
